#!/usr/bin/bash

#go install
wget https://go.dev/dl/go1.21.1.linux-amd64.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.1.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin

#by APT
apt update && apt upgrade -y
apt install pip -y

#httpx install
go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

